// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpMk9f-I9v_K6wASv9dSyluSbqE6GH3lM',
    appId: '1:163840517534:web:fbf284e6b28117426aa28f',
    messagingSenderId: '163840517534',
    projectId: 'whatsapp-clone-359ef',
    authDomain: 'whatsapp-clone-359ef.firebaseapp.com',
    storageBucket: 'whatsapp-clone-359ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjzkvvfkW2UIzqqZo8J9Yix_PXCkm4dRA',
    appId: '1:163840517534:android:cc25dbc8d9f428986aa28f',
    messagingSenderId: '163840517534',
    projectId: 'whatsapp-clone-359ef',
    storageBucket: 'whatsapp-clone-359ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf9cnED3xYHuYJx6RpGtUUMiTXpbwtSvg',
    appId: '1:163840517534:ios:16f9651cafc09cc26aa28f',
    messagingSenderId: '163840517534',
    projectId: 'whatsapp-clone-359ef',
    storageBucket: 'whatsapp-clone-359ef.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf9cnED3xYHuYJx6RpGtUUMiTXpbwtSvg',
    appId: '1:163840517534:ios:8d8fd3ae7f8e24a26aa28f',
    messagingSenderId: '163840517534',
    projectId: 'whatsapp-clone-359ef',
    storageBucket: 'whatsapp-clone-359ef.appspot.com',
    iosBundleId: 'com.example.whatsapp.RunnerTests',
  );
}
