name: whatsapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.6
  country_picker: ^2.0.22
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  firebase_storage: ^11.5.1
  flutter_riverpod: ^2.0.0-dev.9
  firebase_app_check: 0.2.1+5
  image_picker: ^1.0.4
  photo_manager: ^3.0.0-dev.2 


flutter_native_splash:
  color: "FFFFFF"
  color_dark: "111B21"
  image: assets/images/loading_light.png
  image_dark: assets/images/loading_dark.png
  android_12:
    color: "FFFFFF"
    color_dark: "111B21"
    image: assets/images/loading_light.png
    image_dark: assets/images/loading_dark.png
    icon_background_color: "FFFFFF"
    icon_background_color_dark: "111B21"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
